### ISSUE TITLE
请问，有新版了没？

### ISSUE THREAD

**Issue by BadDeveloper2022** [xinjianteng/Leoric#2]
请问，有新版了没？
我想用这个保活App
别的都不行，尤其是 OS0 9  10 上

**Comment by BadDeveloper2022** [comment]
Android 6.0 没有作用
直接运行Demo的
进程还是被杀了
还有Service的Oncreate 不停地被调用

**Comment by xinjianteng** [comment]
> 请问，有新版了没？
> 我想用这个保活App
> 别的都不行，尤其是 OS0 9 10 上

有什么问题吗？
